dist: trusty
sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 3.5
      env: TOXENV=codecov

addons:
  sonarcloud:
    organization: "alex-dow-github"
    token:
      secure: bc95a77f571eda95ccf20df4df8df623832e5154


install:
  - pip install tox
script:
  - tox
